### ISSUE TITLE
Fresh start errors out

### ISSUE THREAD

**Issue by lexisother** [chelnak/gh-changelog#132]
I just installed `gh` and ran `gh auth` to log into my account, then installed the extension, and ran `gh changelog new` in one of my repositories. I was greeted with the following error:

```
└─$ gh changelog new

❌ It looks like something went wrong!

Reported errors:
• could not create initial client: authentication token not found for host github.com
```

Any ideas? `gh` itself works fine.

**Comment by chelnak** [comment]
Hey, this is certainly interesting. I'll take a look.

Thank you for opening the issue!

**Comment by chelnak** [comment]
@lexisother This should be fixed now.

A new release will be available within the hour.
