### ISSUE TITLE
Produces only a bare changelog

### ISSUE THREAD

**Issue by rcoundon** [chelnak/gh-changelog#19]
I really like the look of this but can't seem to get it to work. I've added the extension and when I run it using 
`gh changelog new` is just get the bare changelog, no commits are extracted or entered into the log. Is there a way to turn on logging to see what's going on or is there something obvious I'm missing?

**Comment by chelnak** [comment]
Hey @rcoundon !

Right now,  changelog generation requires that:

- you are running from inside a local git repo
- you are using tags to mark releases
- you are following a pull-request workflow

Is the above true for your environment?

With regards to logging, it's not there right now. It's still early days for the extension, however it's a valid ask and something I think would be nice to consider!

Also I would really like to support commit entries in the future.. it's got the potential to increase the value for users.

Thanks!

**Comment by rcoundon** [comment]
Thanks for getting back to me so quickly. We're not using tags at the moment (but should be), the other requirements are met though.
I think it's worth adding what's supported into the readme as I wasn't sure what to expect in terms of functionality.

Support for commit entries would be excellent!

**Comment by rcoundon** [comment]
> Thank you for the feedback! I agree, the README needs updating!
> 
> I'll get that sorted soon.
Excellent
> 
> Out of curiosity, in your current workflow, how would you envision this tool working? E.g as a user what would you expect?

To be honest, I hadn't thought about it in any depth, was more just curious to see what the tool did.
Thinking it through, it'd be great to be able to use it to show the list of commits that had been made that roll up to the tags for releases.

**Comment by chelnak** [comment]
Hey @chelnak I'm going to close this issue now given that there are no outstanding actions.

I created #22 a while back to track the request for commits.

Thanks for your feedback!
