### ISSUE TITLE
Generated changelog should pass basic markdown linting

### ISSUE THREAD

**Issue by chelnak** [chelnak/gh-changelog#7]

**Comment by adriens** [comment]
Did you get the `md` by redirecting output with `>` ?

**Comment by chelnak** [comment]
Hey! Sorry I missed this.

No , the magic happens in the method: https://github.com/chelnak/gh-changelog/blob/main/internal/pkg/writer/writer.go

**Comment by adriens** [comment]
Sorry for bothering you, but could you drop a snippet in the README that explains how to generate the markdown file ? :pray:

**Comment by chelnak** [comment]
The latest release will generate it for you. You may need to update you binary.

Run `gh extension upgrade chelnak/gh-changelog` then `gh extension new`

You should get a `CHANGELOG.md` file in the root of your repository.

I will add some more clarification to the README though. Hope this helps 😄

**Comment by adriens** [comment]
I'm giving it a try right now :rocket:

**Comment by adriens** [comment]
it does perfectly the job :muscle: 
Thanks a lot for your feedback :smile_cat:

**Comment by adriens** [comment]
Being able to view it from the terminal also is a cool feature :sparkler:

**Comment by chelnak** [comment]
Thank you! 😄
