### ISSUE TITLE
Command `gh changelog new` fails when there are no tags

### ISSUE THREAD

**Issue by chelnak** [chelnak/gh-changelog#90]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/3777574/178473465-10f11896-b4d8-45cf-b2ba-f783513cb05d.png">

**Comment by Jordan-Dennis** [comment]
Hi @chelnak,
I have not been able to get `gh changelog` to find my `tag`s. Here is the output of `git tag`,
![image](https://user-images.githubusercontent.com/93350879/213035225-3c7edbf5-87be-46b3-8fb1-b2cf36b0df1d.png)
and here is the output of `gh changelog new`
![image](https://user-images.githubusercontent.com/93350879/213035267-1bd9a595-faa2-4c96-ba9e-59a087dd6b81.png)
Regards
Jordan

**Comment by chelnak** [comment]
Hey @Jordan-Dennis, right now the tags need to be present on GitHub as we consume data from their API.

If you run git push --follow-tags and run the command again, does it work?

Maybe the error message here could be more descriptive.

**Comment by Jordan-Dennis** [comment]
Thanks @chelnak,
that worked now, but there is not a lot of information available in the `CHANGELOG.md`. Is there some way of making it display more information (i.e. flags in the commits ect)?
Regards
Jordan

**Comment by Jordan-Dennis** [comment]
Oh, I see, it is about the tags in the PRs.

**Comment by chelnak** [comment]
Hey. So it aggregates the PRs in between each tag. There should also be a link to the comparison between tags where you can see the commits.

**Comment by Jordan-Dennis** [comment]
Awesome thanks.
